version: '3.8'
services:
  db:
    image: postgres:15
    container_name: history_bot_db
    restart: always
    environment:
      POSTGRES_USER: ArtStar
      POSTGRES_PASSWORD: 52@jdpbQ
      POSTGRES_DB: history_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: history_bot_app
    restart: always
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/history_bot
      - DB_USER=${DB_USER:-ArtStar}
      - DB_PASSWORD=${DB_PASSWORD:-52@jdpbQ}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}

volumes:
  postgres_data:
